name: training_book_store
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^17.1.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  logging: ^1.2.0
  pretty_dio_logger: ^1.3.1
  rive: ^0.13.4
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
